// Este archivo fue generado automáticamente
export const emotes = [
  { name: "AppJedi", filename: "AppJedi.gif", preview: "AppJedi.png" },
  { name: "CuteGuyActuallyFlipsPaper", filename: "CuteGuyActuallyFlipsPaper.gif", preview: "CuteGuyActuallyFlipsPaper.png" },
  { name: "Doggo_wink", filename: "Doggo_wink.png" },
  { name: "Dumbass", filename: "Dumbass.png" },
  { name: "Eii", filename: "Eii.png" },
  { name: "FalloutLewd", filename: "FalloutLewd.png" },
  { name: "Ferrari_Logo", filename: "Ferrari_Logo.png" },
  { name: "Haas_Logo", filename: "Haas_Logo.png" },
  { name: "KEKW", filename: "KEKW.png" },
  { name: "McLaren_Logo", filename: "McLaren_Logo.png" },
  { name: "Mercedes_Logo", filename: "Mercedes_Logo.png" },
  { name: "PepeHands", filename: "PepeHands.png" },
  { name: "PepeSmoke", filename: "PepeSmoke.gif", preview: "PepeSmoke.png" },
  { name: "PepegaCredit", filename: "PepegaCredit.gif", preview: "PepegaCredit.png" },
  { name: "RedBull_Logo", filename: "RedBull_Logo.png" },
  { name: "TipsFedora", filename: "TipsFedora.png" },
  { name: "Williams_Logo", filename: "Williams_Logo.png" },
  { name: "aaaa", filename: "aaaa.png" },
  { name: "active-developer-badge", filename: "active-developer-badge.png" },
  { name: "adult", filename: "adult.png" },
  { name: "albon", filename: "albon.png" },
  { name: "alchurself", filename: "alchurself.gif", preview: "alchurself.png" },
  { name: "alonso-lmoa", filename: "alonso-lmoa.png" },
  { name: "baddie-patrick", filename: "baddie-patrick.png" },
  { name: "bank", filename: "bank.png" },
  { name: "bbpepo-minecraft-bed", filename: "bbpepo-minecraft-bed.gif", preview: "bbpepo-minecraft-bed.png" },
  { name: "beluga", filename: "beluga.png" },
  { name: "blehh-cat", filename: "blehh-cat.png" },
  { name: "bobhigh", filename: "bobhigh.png" },
  { name: "bookpepegogogo", filename: "bookpepegogogo.gif", preview: "bookpepegogogo.png" },
  { name: "books", filename: "books.png" },
  { name: "bottas", filename: "bottas.png" },
  { name: "bribe", filename: "bribe.png" },
  { name: "bruh", filename: "bruh.png" },
  { name: "cat-bitting", filename: "cat-bitting.gif", preview: "cat-bitting.png" },
  { name: "cat-cips", filename: "cat-cips.gif", preview: "cat-cips.png" },
  { name: "cat-combing", filename: "cat-combing.gif", preview: "cat-combing.png" },
  { name: "cat-cry", filename: "cat-cry.png" },
  { name: "cat-dance", filename: "cat-dance.gif", preview: "cat-dance.png" },
  { name: "cat-dance2", filename: "cat-dance2.gif", preview: "cat-dance2.png" },
  { name: "cat-dead", filename: "cat-dead.gif", preview: "cat-dead.png" },
  { name: "cat-explode", filename: "cat-explode.gif", preview: "cat-explode.png" },
  { name: "cat-jam", filename: "cat-jam.gif", preview: "cat-jam.png" },
  { name: "cat-nope", filename: "cat-nope.gif", preview: "cat-nope.png" },
  { name: "cat-party", filename: "cat-party.gif", preview: "cat-party.png" },
  { name: "cat-point-and-laugh", filename: "cat-point-and-laugh.png" },
  { name: "cat-punch", filename: "cat-punch.gif", preview: "cat-punch.png" },
  { name: "cat-shocked", filename: "cat-shocked.gif", preview: "cat-shocked.png" },
  { name: "cat-sus", filename: "cat-sus.png" },
  { name: "cat-washing-clothes", filename: "cat-washing-clothes.gif", preview: "cat-washing-clothes.png" },
  { name: "cat-wej", filename: "cat-wej.png" },
  { name: "cat-yipee", filename: "cat-yipee.gif", preview: "cat-yipee.png" },
  { name: "cat", filename: "cat.gif", preview: "cat.png" },
  { name: "cat", filename: "cat.png" },
  { name: "cat2", filename: "cat2.png" },
  { name: "cat3", filename: "cat3.gif", preview: "cat3.png" },
  { name: "catJAM", filename: "catJAM.gif", preview: "catJAM.png" },
  { name: "catboom-a", filename: "catboom-a.gif", preview: "catboom-a.png" },
  { name: "catcry", filename: "catcry.gif", preview: "catcry.png" },
  { name: "catdespair", filename: "catdespair.png" },
  { name: "cathehe", filename: "cathehe.png" },
  { name: "catkiss", filename: "catkiss.gif", preview: "catkiss.png" },
  { name: "catshake", filename: "catshake.gif", preview: "catshake.png" },
  { name: "catsittingverycomfortable", filename: "catsittingverycomfortable.png" },
  { name: "catuwu", filename: "catuwu.gif", preview: "catuwu.png" },
  { name: "caught-in-4k", filename: "caught-in-4k.png" },
  { name: "ce-dogelook", filename: "ce-dogelook.png" },
  { name: "certified-moderator", filename: "certified-moderator.png" },
  { name: "cheerpepe", filename: "cheerpepe.gif", preview: "cheerpepe.png" },
  { name: "cheeserhaha", filename: "cheeserhaha.gif", preview: "cheeserhaha.png" },
  { name: "chefkiss", filename: "chefkiss.png" },
  { name: "chipichapa", filename: "chipichapa.gif", preview: "chipichapa.png" },
  { name: "christian-999", filename: "christian-999.png" },
  { name: "closeuppatrick", filename: "closeuppatrick.png" },
  { name: "completed-quest", filename: "completed-quest.png" },
  { name: "copium", filename: "copium.png" },
  { name: "cry", filename: "cry.gif", preview: "cry.png" },
  { name: "crythumbsup", filename: "crythumbsup.png" },
  { name: "cummer", filename: "cummer.png" },
  { name: "cursed-dog", filename: "cursed-dog.png" },
  { name: "cursed-dolphin-meme", filename: "cursed-dolphin-meme.png" },
  { name: "cursed-eagle-stare", filename: "cursed-eagle-stare.png" },
  { name: "dance", filename: "dance.gif", preview: "dance.png" },
  { name: "darkpet", filename: "darkpet.gif", preview: "darkpet.png" },
  { name: "dawg", filename: "dawg.gif", preview: "dawg.png" },
  { name: "desperatecat", filename: "desperatecat.gif", preview: "desperatecat.png" },
  { name: "diamond", filename: "diamond.png" },
  { name: "discord-bug-hunter", filename: "discord-bug-hunter.png" },
  { name: "discord-gold-bug-hunter", filename: "discord-gold-bug-hunter.png" },
  { name: "discord-staff", filename: "discord-staff.png" },
  { name: "dog-happy-ears", filename: "dog-happy-ears.gif", preview: "dog-happy-ears.png" },
  { name: "dog-run", filename: "dog-run.gif", preview: "dog-run.png" },
  { name: "dog-snif", filename: "dog-snif.gif", preview: "dog-snif.png" },
  { name: "dog-wtf", filename: "dog-wtf.png" },
  { name: "dog", filename: "dog.gif", preview: "dog.png" },
  { name: "dog_dance", filename: "dog_dance.gif", preview: "dog_dance.png" },
  { name: "dogavoidingtouch", filename: "dogavoidingtouch.gif", preview: "dogavoidingtouch.png" },
  { name: "doge-cute", filename: "doge-cute.png" },
  { name: "doge-shocked", filename: "doge-shocked.png" },
  { name: "dogeatingwatermelon", filename: "dogeatingwatermelon.gif", preview: "dogeatingwatermelon.png" },
  { name: "dogekek", filename: "dogekek.png" },
  { name: "doggy-boop", filename: "doggy-boop.gif", preview: "doggy-boop.png" },
  { name: "doggy-mad", filename: "doggy-mad.png" },
  { name: "dogrrr", filename: "dogrrr.png" },
  { name: "dr3-shh", filename: "dr3-shh.png" },
  { name: "dr3heart", filename: "dr3heart.png" },
  { name: "dr3simp", filename: "dr3simp.png" },
  { name: "duck-jump", filename: "duck-jump.gif", preview: "duck-jump.png" },
  { name: "duck", filename: "duck.gif", preview: "duck.png" },
  { name: "duckcowering", filename: "duckcowering.gif", preview: "duckcowering.png" },
  { name: "duckdance", filename: "duckdance.gif", preview: "duckdance.png" },
  { name: "duckduck", filename: "duckduck.gif", preview: "duckduck.png" },
  { name: "duckwaddle", filename: "duckwaddle.gif", preview: "duckwaddle.png" },
  { name: "duckyleon", filename: "duckyleon.png" },
  { name: "early-supporter", filename: "early-supporter.png" },
  { name: "early-verified-bot-developer", filename: "early-verified-bot-developer.png" },
  { name: "emerald", filename: "emerald.png" },
  { name: "evilcat", filename: "evilcat.png" },
  { name: "evolving-badge-nitro-1-months", filename: "evolving-badge-nitro-1-months.png" },
  { name: "evolving-badge-nitro-12", filename: "evolving-badge-nitro-12.png" },
  { name: "evolving-badge-nitro-15-months", filename: "evolving-badge-nitro-15-months.png" },
  { name: "evolving-badge-nitro-18-months", filename: "evolving-badge-nitro-18-months.png" },
  { name: "evolving-badge-nitro-2-months", filename: "evolving-badge-nitro-2-months.png" },
  { name: "evolving-badge-nitro-24-months", filename: "evolving-badge-nitro-24-months.png" },
  { name: "evolving-badge-nitro-3-months", filename: "evolving-badge-nitro-3-months.png" },
  { name: "evolving-badge-nitro-6-months", filename: "evolving-badge-nitro-6-months.png" },
  { name: "evolving-badge-nitro-9-months", filename: "evolving-badge-nitro-9-months.png" },
  { name: "f1-logo", filename: "f1-logo.png" },
  { name: "f1alpinelogo", filename: "f1alpinelogo.png" },
  { name: "f1nico", filename: "f1nico.png" },
  { name: "f1pain", filename: "f1pain.png" },
  { name: "fachero", filename: "fachero.png" },
  { name: "falloutbop", filename: "falloutbop.gif", preview: "falloutbop.png" },
  { name: "feliz", filename: "feliz.png" },
  { name: "fell-for-it-again-award", filename: "fell-for-it-again-award.png" },
  { name: "fiesta", filename: "fiesta.png" },
  { name: "frog-walk", filename: "frog-walk.gif", preview: "frog-walk.png" },
  { name: "frog", filename: "frog.png" },
  { name: "gg", filename: "gg.png" },
  { name: "gladgers", filename: "gladgers.png" },
  { name: "gnome", filename: "gnome.png" },
  { name: "gnomedance", filename: "gnomedance.gif", preview: "gnomedance.png" },
  { name: "gnomepog", filename: "gnomepog.png" },
  { name: "gold", filename: "gold.png" },
  { name: "good", filename: "good.png" },
  { name: "goodboy", filename: "goodboy.gif", preview: "goodboy.png" },
  { name: "gratz", filename: "gratz.png" },
  { name: "gtapicknose", filename: "gtapicknose.png" },
  { name: "gtayummy", filename: "gtayummy.png" },
  { name: "guenther", filename: "guenther.png" },
  { name: "gumball", filename: "gumball.png" },
  { name: "happy-cat", filename: "happy-cat.png" },
  { name: "harrypotter", filename: "harrypotter.gif", preview: "harrypotter.png" },
  { name: "hehehe", filename: "hehehe.gif", preview: "hehehe.png" },
  { name: "hola", filename: "hola.png" },
  { name: "huh", filename: "huh.gif", preview: "huh.png" },
  { name: "huhcat", filename: "huhcat.png" },
  { name: "huhh-smoother", filename: "huhh-smoother.gif", preview: "huhh-smoother.png" },
  { name: "hypesquad-balance", filename: "hypesquad-balance.png" },
  { name: "hypesquad-bravery", filename: "hypesquad-bravery.png" },
  { name: "hypesquad-brilliance", filename: "hypesquad-brilliance.png" },
  { name: "hypesquad-events", filename: "hypesquad-events.png" },
  { name: "imgoingcrazy", filename: "imgoingcrazy.gif", preview: "imgoingcrazy.png" },
  { name: "iron", filename: "iron.png" },
  { name: "irongolem", filename: "irongolem.gif", preview: "irongolem.png" },
  { name: "john-pork", filename: "john-pork.png" },
  { name: "keks", filename: "keks.png" },
  { name: "kitty-blush", filename: "kitty-blush.png" },
  { name: "lando-banana", filename: "lando-banana.png" },
  { name: "lando-thumbsup", filename: "lando-thumbsup.png" },
  { name: "lapis-lazuli", filename: "lapis-lazuli.png" },
  { name: "leclerc-cl16-ferrari-f1", filename: "leclerc-cl16-ferrari-f1.png" },
  { name: "leclerc-cringe", filename: "leclerc-cringe.png" },
  { name: "licka", filename: "licka.gif", preview: "licka.png" },
  { name: "lipstickslay", filename: "lipstickslay.gif", preview: "lipstickslay.png" },
  { name: "loafofbreaddoge", filename: "loafofbreaddoge.png" },
  { name: "long-doggo-boop", filename: "long-doggo-boop.gif", preview: "long-doggo-boop.png" },
  { name: "lul", filename: "lul.png" },
  { name: "mad", filename: "mad.png" },
  { name: "max-shrug", filename: "max-shrug.png" },
  { name: "megareverse-1", filename: "megareverse-1.png" },
  { name: "messyeater", filename: "messyeater.png" },
  { name: "middle-finger-cat", filename: "middle-finger-cat.png" },
  { name: "minecraft-dogo", filename: "minecraft-dogo.png" },
  { name: "minecraft-mundo", filename: "minecraft-mundo.png" },
  { name: "minecraft-rose-bush", filename: "minecraft-rose-bush.png" },
  { name: "minecraft-sheepspin", filename: "minecraft-sheepspin.gif", preview: "minecraft-sheepspin.png" },
  { name: "minecraft", filename: "minecraft.png" },
  { name: "minecraft2", filename: "minecraft2.gif", preview: "minecraft2.png" },
  { name: "minecraftcube", filename: "minecraftcube.gif", preview: "minecraftcube.png" },
  { name: "mmmm", filename: "mmmm.png" },
  { name: "modash", filename: "modash.png" },
  { name: "moderator-programs-alumni", filename: "moderator-programs-alumni.png" },
  { name: "muerto", filename: "muerto.png" },
  { name: "nerd-pepe", filename: "nerd-pepe.gif", preview: "nerd-pepe.png" },
  { name: "nether-quartz", filename: "nether-quartz.png" },
  { name: "nice", filename: "nice.png" },
  { name: "noob-osrs", filename: "noob-osrs.png" },
  { name: "obunga", filename: "obunga.png" },
  { name: "omegalul", filename: "omegalul.png" },
  { name: "orbs-discord", filename: "orbs-discord.png" },
  { name: "originally-known-as", filename: "originally-known-as.png" },
  { name: "osrsHelmie", filename: "osrsHelmie.png" },
  { name: "parrotvibe", filename: "parrotvibe.gif", preview: "parrotvibe.png" },
  { name: "partnered-server-owner", filename: "partnered-server-owner.png" },
  { name: "patrick", filename: "patrick.png" },
  { name: "patrickfab", filename: "patrickfab.png" },
  { name: "patrickrope", filename: "patrickrope.png" },
  { name: "peepoSignedSimp", filename: "peepoSignedSimp.gif", preview: "peepoSignedSimp.png" },
  { name: "peepomine", filename: "peepomine.png" },
  { name: "peeponewplayer", filename: "peeponewplayer.png" },
  { name: "pengubook", filename: "pengubook.png" },
  { name: "pepe-disappear", filename: "pepe-disappear.gif", preview: "pepe-disappear.png" },
  { name: "pepe-overcursed", filename: "pepe-overcursed.png" },
  { name: "pepe1", filename: "pepe1.gif", preview: "pepe1.png" },
  { name: "pepe_tipsfedora", filename: "pepe_tipsfedora.png" },
  { name: "pepeangry", filename: "pepeangry.png" },
  { name: "pepeboxing", filename: "pepeboxing.png" },
  { name: "pepeburger", filename: "pepeburger.png" },
  { name: "pepeccolo", filename: "pepeccolo.png" },
  { name: "pepechristmashype", filename: "pepechristmashype.gif", preview: "pepechristmashype.png" },
  { name: "pepechristmasjammies", filename: "pepechristmasjammies.gif", preview: "pepechristmasjammies.png" },
  { name: "pepedance", filename: "pepedance.gif", preview: "pepedance.png" },
  { name: "pepedumb", filename: "pepedumb.png" },
  { name: "pepefrog", filename: "pepefrog.gif", preview: "pepefrog.png" },
  { name: "pepegiveme", filename: "pepegiveme.png" },
  { name: "pepegun", filename: "pepegun.png" },
  { name: "pepehi", filename: "pepehi.png" },
  { name: "pepeiseeu", filename: "pepeiseeu.png" },
  { name: "pepeloading", filename: "pepeloading.png" },
  { name: "pepemad", filename: "pepemad.png" },
  { name: "pepepray", filename: "pepepray.png" },
  { name: "pepesalute", filename: "pepesalute.png" },
  { name: "pepethinking", filename: "pepethinking.png" },
  { name: "pepewhoa", filename: "pepewhoa.png" },
  { name: "pepeworrypat", filename: "pepeworrypat.png" },
  { name: "peppaflop", filename: "peppaflop.png" },
  { name: "pig", filename: "pig.png" },
  { name: "pipboy", filename: "pipboy.png" },
  { name: "podium", filename: "podium.png" },
  { name: "pogdog", filename: "pogdog.gif", preview: "pogdog.png" },
  { name: "pomhappy", filename: "pomhappy.png" },
  { name: "popcat", filename: "popcat.gif", preview: "popcat.png" },
  { name: "psychocheco", filename: "psychocheco.png" },
  { name: "pugdancer", filename: "pugdancer.gif", preview: "pugdancer.png" },
  { name: "racingbulls", filename: "racingbulls.png" },
  { name: "ragey", filename: "ragey.gif", preview: "ragey.png" },
  { name: "rainbow-minecraft-parrot-dances", filename: "rainbow-minecraft-parrot-dances.gif", preview: "rainbow-minecraft-parrot-dances.png" },
  { name: "ratdog", filename: "ratdog.png" },
  { name: "realistic-thumbs-up", filename: "realistic-thumbs-up.png" },
  { name: "redstone", filename: "redstone.png" },
  { name: "runescape-dance", filename: "runescape-dance.gif", preview: "runescape-dance.png" },
  { name: "sabiondo", filename: "sabiondo.png" },
  { name: "sadcat", filename: "sadcat.gif", preview: "sadcat.png" },
  { name: "sadcat", filename: "sadcat.png" },
  { name: "sadcheeser", filename: "sadcheeser.png" },
  { name: "sadvettel", filename: "sadvettel.png" },
  { name: "santoperonotanto", filename: "santoperonotanto.png" },
  { name: "screaming-chihuahua", filename: "screaming-chihuahua.png" },
  { name: "shibateeth", filename: "shibateeth.gif", preview: "shibateeth.png" },
  { name: "shrug", filename: "shrug.png" },
  { name: "simp1", filename: "simp1.png" },
  { name: "skull", filename: "skull.png" },
  { name: "skully", filename: "skully.gif", preview: "skully.png" },
  { name: "smartguy", filename: "smartguy.gif", preview: "smartguy.png" },
  { name: "smile", filename: "smile.png" },
  { name: "smugbob3", filename: "smugbob3.png" },
  { name: "sneaky", filename: "sneaky.png" },
  { name: "snowball", filename: "snowball.png" },
  { name: "soy2", filename: "soy2.gif", preview: "soy2.png" },
  { name: "soy3", filename: "soy3.gif", preview: "soy3.png" },
  { name: "soychicken", filename: "soychicken.png" },
  { name: "soydebate", filename: "soydebate.png" },
  { name: "soyjak-point", filename: "soyjak-point.png" },
  { name: "soyjaklaugh", filename: "soyjaklaugh.gif", preview: "soyjaklaugh.png" },
  { name: "soypoint", filename: "soypoint.png" },
  { name: "spongebob-fish", filename: "spongebob-fish.png" },
  { name: "spongebob-plankton", filename: "spongebob-plankton.png" },
  { name: "stinky", filename: "stinky.png" },
  { name: "subscriber-nitro", filename: "subscriber-nitro.png" },
  { name: "suds", filename: "suds.png" },
  { name: "supersad", filename: "supersad.png" },
  { name: "sweetdog", filename: "sweetdog.gif", preview: "sweetdog.png" },
  { name: "thevoices", filename: "thevoices.gif", preview: "thevoices.png" },
  { name: "toto", filename: "toto.png" },
  { name: "trashyaxolotl", filename: "trashyaxolotl.png" },
  { name: "triste", filename: "triste.png" },
  { name: "typingcat", filename: "typingcat.gif", preview: "typingcat.png" },
  { name: "uno-reverse", filename: "uno-reverse.png" },
  { name: "uwu-duck", filename: "uwu-duck.png" },
  { name: "vaultboy", filename: "vaultboy.png" },
  { name: "verstappen-really", filename: "verstappen-really.png" },
  { name: "verycat", filename: "verycat.gif", preview: "verycat.png" },
  { name: "vintagetypewriter", filename: "vintagetypewriter.png" },
  { name: "warden-minecraft", filename: "warden-minecraft.gif", preview: "warden-minecraft.png" },
  { name: "warjak", filename: "warjak.png" },
  { name: "wauw", filename: "wauw.png" },
  { name: "welcome", filename: "welcome.png" },
  { name: "what", filename: "what.png" },
  { name: "yukistare2", filename: "yukistare2.png" },
  { name: "zazuthousandyardstare", filename: "zazuthousandyardstare.png" }
];
